id: P001662
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:13:12.536677
source_metadata:
  id: bdr:W25815
  title: རྙིང་མ་རྒྱུད་འབུམ་གྱི་ཁ་སྐོང ༼མཚམས་བྲག་དགོན་པའི་བྲིས་མ༽
  author: ''
  volumes:
    e51c289d4f3e480e842e3c96091a36fe:
      image_group_id: I3900
      title: ''
      volume_number: 1
      total_pages: 690
      base_file: v001.txt
    6347897ace994b05b6064c6b07eb3d16:
      image_group_id: I3901
      title: ''
      volume_number: 2
      total_pages: 634
      base_file: v002.txt
    be22ec7ed53442c581a4c68df04ae759:
      image_group_id: I3902
      title: ''
      volume_number: 3
      total_pages: 630
      base_file: v003.txt
    51f1db2e5ccf4c0a921cb736585abacf:
      image_group_id: I3903
      title: ''
      volume_number: 4
      total_pages: 676
      base_file: v004.txt
    f2d03ead8e5140b2ae0274952b1caa7a:
      image_group_id: I3904
      title: ''
      volume_number: 5
      total_pages: 654
      base_file: v005.txt
    164883d7f3974565ac833231b2cf6cc6:
      image_group_id: I3905
      title: ''
      volume_number: 6
      total_pages: 648
      base_file: v006.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
