id: I5975E59C
legacy_id: P001662
ocr_import_info:
  bdrc_scan_id: W25815
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T16:38:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T06:13:41.601788+00:00'
last_modified: 2022-09-02 14:17:16.340400
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W25815
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW25815
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྙིང་མ་རྒྱུད་འབུམ་གྱི་ཁ་སྐོང ༼མཚམས་བྲག་དགོན་པའི་བྲིས་མ༽
statistics:
  ocr_word_mean_confidence_index: 0.7502391713283569
  ocr_word_median_confidence_index: 0.8199999928474426
quality: null
bases:
  I3901:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3901
      total_pages: 634
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3901.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.7166570039087512
    legacy_id: v002
  I3902:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3902
      total_pages: 630
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3902.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6972226077460252
    legacy_id: v003
  I3905:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3905
      total_pages: 648
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I3905.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.8723438005746376
    legacy_id: v006
  I3900:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3900
      total_pages: 690
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3900.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.6805452779568085
    legacy_id: v001
  I3903:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3903
      total_pages: 676
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3903.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7366474093487666
    legacy_id: v004
  I3904:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3904
      total_pages: 654
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3904.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.8752810599450367
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
